name: Build Tweak dylib
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      - name: 安装基础依赖
        run: |
          sudo apt update
          sudo apt install git make clang libxml2-dev curl -y

      - name: 部署Theos
        run: |
          git clone https://github.com/theos/theos.git ~/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          # 重点：直接下载ldid，不再apt安装
          curl -L https://github.com/theos/ldid/releases/latest/download/ldid-linux-arm64 -o ~/theos/bin/ldid
          chmod +x ~/theos/bin/ldid

      - name: 编译打包
        run: |
          make clean
          make package

      - name: 上传成品deb
        uses: actions/upload-artifact@v4
        with:
          name: 弹窗插件成品
          path: packages/*.deb
